# Generated by Django 4.2.3 on 2024-01-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0021_profile_page_alter_create_group_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_page',
        ),
    ]
