# Generated by Django 4.2.3 on 2024-01-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0032_about_page_about_service_page_about_team_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_page',
        ),
    ]
