# Generated by Django 4.2.3 on 2024-01-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0035_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilephoto',
        ),
    ]
