# Generated by Django 4.2.3 on 2024-01-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0044_profilevideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilevideo',
        ),
    ]
