# Generated by Django 4.2.3 on 2024-01-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0048_profilevideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilevideo',
        ),
    ]
