# Generated by Django 4.2.3 on 2024-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0051_delete_profilevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilevideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='profilephoto/image')),
            ],
        ),
    ]
