# Generated by Django 4.2.3 on 2024-01-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0058_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilephoto',
        ),
    ]
