# Generated by Django 4.2.3 on 2024-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0059_delete_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilephoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='profilephoto/image')),
            ],
        ),
    ]
