# Generated by Django 4.2.3 on 2024-01-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0062_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
