# Generated by Django 4.2.3 on 2024-02-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0068_profilevideo_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_group',
        ),
    ]
