# Generated by Django 4.2.3 on 2024-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0070_create_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20)),
                ('singername', models.CharField(max_length=20)),
                ('singerprofession', models.CharField(max_length=20)),
                ('singeraddress', models.CharField(max_length=20)),
                ('singerimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='createsingerimage/image')),
                ('singerinstagramid', models.CharField(max_length=50)),
                ('singerlinkedinid', models.CharField(max_length=50)),
                ('musicianname', models.CharField(max_length=20)),
                ('musicianprofession', models.CharField(max_length=20)),
                ('musicianaddress', models.CharField(max_length=20)),
                ('musicianimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='musicianimage/image')),
                ('musicianinstagramid', models.CharField(max_length=50)),
                ('musicianlinkedinid', models.CharField(max_length=50)),
                ('vname', models.CharField(max_length=20)),
                ('vprofession', models.CharField(max_length=20)),
                ('vaddress', models.CharField(max_length=20)),
                ('vimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='vocalistimage/image')),
                ('vinstagramid', models.CharField(max_length=50)),
                ('vlinkedinid', models.CharField(max_length=50)),
                ('gname', models.CharField(max_length=20)),
                ('gprofession', models.CharField(max_length=20)),
                ('gaddress', models.CharField(max_length=20)),
                ('gimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='guitaristimage/image')),
                ('ginstagramid', models.CharField(max_length=50)),
                ('glinkedinid', models.CharField(max_length=50)),
                ('groupdescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
