# Generated by Django 4.2.3 on 2024-02-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0071_create_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_group',
        ),
    ]
