# Generated by Django 4.2.3 on 2024-02-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0075_create_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_bands',
        ),
    ]
