# Generated by Django 4.2.3 on 2024-02-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0077_create_bands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_bands',
        ),
    ]
