# Generated by Django 4.2.3 on 2024-02-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0079_create_bands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_group',
        ),
    ]
