# Generated by Django 4.2.3 on 2024-02-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0081_create_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_bands',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
