# Generated by Django 4.2.3 on 2024-02-11 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clapStationWebsite', '0082_delete_create_bands_delete_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_bands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandname', models.CharField(max_length=20)),
                ('bandbudget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bandaddress', models.TextField()),
                ('bandimage', models.ImageField(blank=True, default='no image', null=True, upload_to='createband/image')),
                ('banddescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
