# Generated by Django 4.2.3 on 2024-02-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clapStationWebsite', '0084_delete_create_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20)),
                ('singername', models.CharField(max_length=20)),
                ('singerprofession', models.CharField(max_length=20)),
                ('singeraddress', models.CharField(max_length=20)),
                ('singerimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='createsingerimage/image')),
                ('singerlinkedinid', models.CharField(max_length=50)),
                ('singerinstagramid', models.CharField(max_length=50)),
                ('singergithubid', models.CharField(max_length=50)),
                ('musicianname', models.CharField(max_length=20)),
                ('musicianprofession', models.CharField(max_length=20)),
                ('musicianaddress', models.CharField(max_length=20)),
                ('musicianimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='musicianimage/image')),
                ('musicianlinkedinid', models.CharField(max_length=50)),
                ('musicianinstagramid', models.CharField(max_length=50)),
                ('musiciangithubid', models.CharField(max_length=50)),
                ('guitaristname', models.CharField(max_length=20)),
                ('guitaristprofession', models.CharField(max_length=20)),
                ('guitaristaddress', models.CharField(max_length=20)),
                ('guitaristimage', models.ImageField(blank=True, default='no image found', null=True, upload_to='guitaristimage/image')),
                ('guitaristlinkedinid', models.CharField(max_length=50)),
                ('guitaristinstagramid', models.CharField(max_length=50)),
                ('guitaristgithubid', models.CharField(max_length=50)),
                ('groupdescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
