# Generated by Django 4.2.3 on 2024-02-13 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clapStationWebsite', '0092_remove_eventimage_event_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('venue', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ticket_price', models.IntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_images/posters')),
                ('images', models.FileField(blank=True, null=True, upload_to='event_images')),
                ('event_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
