# Generated by Django 4.2.3 on 2024-02-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clapStationWebsite', '0095_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.commentsection')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=130)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event_detail_page',
        ),
        migrations.AddField(
            model_name='commentsection',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.postcomment'),
        ),
        migrations.AddField(
            model_name='commentsection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
