# Generated by Django 4.2.3 on 2024-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0096_commentsection_postcomment_delete_event_detail_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_our_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_mission/')),
            ],
        ),
        migrations.CreateModel(
            name='About_our_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_value/')),
            ],
        ),
        migrations.CreateModel(
            name='About_our_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_vision/')),
            ],
        ),
    ]
