# Generated by Django 4.2.3 on 2024-02-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0097_about_our_mission_about_our_value_about_our_vision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_our_value',
        ),
        migrations.DeleteModel(
            name='About_our_vision',
        ),
    ]
