# Generated by Django 4.2.3 on 2024-02-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0098_delete_about_our_value_delete_about_our_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=600)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('poster1', models.ImageField(blank=True, null=True, upload_to='academic_images/posters1')),
                ('poster2', models.ImageField(blank=True, null=True, upload_to='academic_images/posters2')),
                ('facebook', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=30)),
                ('mentor_profession', models.CharField(max_length=30)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.academic_page')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='academic_images/gallary')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.academic_page')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_feestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('functionality1', models.CharField(max_length=30)),
                ('functionality2', models.CharField(max_length=30)),
                ('functionality3', models.CharField(max_length=30)),
                ('functionality4', models.CharField(max_length=30)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.academic_page')),
            ],
        ),
    ]
