# Generated by Django 4.2.3 on 2024-02-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0099_academic_page_academic_mentor_academic_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academic_Mentor',
        ),
    ]
