# Generated by Django 4.2.3 on 2024-02-16 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0100_delete_academic_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_image', models.ImageField(blank=True, null=True, upload_to='academic_images/mentor_image')),
                ('mentor_name', models.CharField(max_length=30)),
                ('mentor_profession', models.CharField(max_length=30)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.academic_page')),
            ],
        ),
    ]
