# Generated by Django 4.2.3 on 2024-02-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0102_comment_delete_commentsection_delete_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
