# Generated by Django 4.2.3 on 2024-02-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0103_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
