# Generated by Django 4.2.3 on 2024-02-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0105_comment_eventbooking_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_reply',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Commentreply',
        ),
    ]
