# Generated by Django 4.2.3 on 2024-02-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0107_comment_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
