# Generated by Django 4.2.3 on 2024-02-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0110_bookatutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAtutor',
        ),
    ]
