# Generated by Django 4.2.3 on 2024-02-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0112_bookatutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
