# Generated by Django 4.2.3 on 2024-02-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0114_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
