# Generated by Django 4.2.3 on 2024-02-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0119_contact_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_info',
        ),
    ]
