# Generated by Django 4.2.3 on 2024-02-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0120_delete_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('mobileno', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=50)),
                ('facebooklink', models.CharField(max_length=50)),
                ('twitterlink', models.CharField(max_length=50)),
                ('instagramlink', models.CharField(max_length=50)),
                ('linedinlink', models.CharField(max_length=50)),
                ('maplink', models.TextField()),
            ],
        ),
    ]
