# Generated by Django 4.2.3 on 2024-02-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0121_contact_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
