# Generated by Django 4.2.3 on 2024-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0123_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_info',
        ),
    ]
