# Generated by Django 4.2.3 on 2024-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0125_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_jamming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Content_show', models.TextField()),
                ('Content_hide', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jamming_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_image', models.ImageField(blank=True, default='', null=True, upload_to='JammingStationImage/')),
                ('title', models.CharField(max_length=100)),
                ('Blog_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jamming_channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YouTube_link', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='JammingStationImage/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jamming_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_image', models.ImageField(blank=True, default='', null=True, upload_to='JammingStationImage/')),
                ('location', models.TextField()),
                ('Event_content', models.TextField()),
                ('Fee', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jamming_titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo_image', models.ImageField(blank=True, default='', null=True, upload_to='JammingStationImage/')),
                ('title', models.CharField(max_length=100)),
                ('Subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
