# Generated by Django 4.2.3 on 2024-02-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0126_about_jamming_jamming_blog_jamming_channel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jamming_Blog',
        ),
        migrations.DeleteModel(
            name='Jamming_Event',
        ),
    ]
