# Generated by Django 4.2.3 on 2024-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0127_delete_jamming_blog_delete_jamming_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_img', models.ImageField(blank=True, default='', null=True, upload_to='JammingStationImage/')),
                ('place_name', models.CharField(max_length=100)),
                ('place_att', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
                ('Low_price', models.CharField(max_length=10)),
                ('high_price', models.CharField(max_length=10)),
                ('NEvent', models.IntegerField()),
                ('Capcity', models.IntegerField()),
            ],
        ),
    ]
