# Generated by Django 4.2.3 on 2024-02-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0130_eventbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
