# Generated by Django 4.2.3 on 2024-02-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0135_bandbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bandbooking',
        ),
    ]
