# Generated by Django 4.2.3 on 2024-02-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0144_tutorcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorcontact',
        ),
    ]
