# Generated by Django 4.2.3 on 2024-02-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0146_delete_about_jamming_delete_booking_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=20)),
                ('numOfcandidate', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.bookatutor')),
            ],
        ),
    ]
