# Generated by Django 4.2.3 on 2024-02-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0147_tutorcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorcontact',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='BookAtutor',
        ),
        migrations.DeleteModel(
            name='Tutorcontact',
        ),
    ]
