# Generated by Django 4.2.3 on 2024-02-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0148_remove_tutorcontact_tutor_delete_bookatutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_fields', models.ImageField(blank=True, default='', null=True, upload_to='profilephoto/image')),
                ('name', models.CharField(max_length=50)),
                ('Profession_title', models.CharField(max_length=100)),
                ('Fee', models.TextField()),
                ('Status', models.CharField(max_length=50)),
                ('SessionDays', models.CharField(max_length=300)),
                ('social_links', models.CharField(blank=True, max_length=100, null=True)),
                ('social_links1', models.CharField(blank=True, max_length=100, null=True)),
                ('social_links2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=20)),
                ('numOfcandidate', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.tutor')),
            ],
        ),
    ]
