# Generated by Django 4.2.3 on 2024-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0150_jamming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jamming',
        ),
    ]
