# Generated by Django 4.2.3 on 2024-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0151_delete_jamming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='jamming/images')),
                ('location', models.TextField(max_length=50)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_space', models.IntegerField()),
                ('number_of_grounds', models.IntegerField()),
            ],
        ),
    ]
