# Generated by Django 4.2.3 on 2024-02-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0153_delete_jamming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('location', models.TextField(max_length=50)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seating_space', models.IntegerField()),
                ('number_of_grounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jammingimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Jammingimages/')),
                ('jamming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.jamming')),
            ],
        ),
        migrations.CreateModel(
            name='jammingcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('jamming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clapStationWebsite.jamming')),
            ],
        ),
    ]
