# Generated by Django 4.2.3 on 2024-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0154_jamming_jammingimage_jammingcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventbooking',
        ),
    ]
